[package]
name = "no56"
version = "0.1.0"
authors = ["sato.naoya <sato.naoya@classmethod.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
